services:
  mysql:
    image: docker.1ms.run/library/mysql:8.0.33
    ports:
      - "3306:3306"
    #    volumes:
    #      - /opt/data/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Secret@123
      MYSQL_DATABASE: chatbot
    #      MYSQL_USER: chatbot_user
    #      MYSQL_PASSWORD: Secret@123
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
    restart: always
    mem_limit: 256m
    cpu_shares: 128

  openldap:
    image: rroemhild/docker-test-openldap:2.1
    ports:
      - "10389:10389"
      - "10636:10636"
    #    volumes:
    #      - /opt/data/ldap_data:/var/lib/ldap
    #      - /opt/data/ldap_config:/etc/ldap/slapd.d
    healthcheck:
      test: [ "CMD", "ldapsearch", "-H", "ldap://localhost:10389", "-x","-b", "ou=people,dc=planetexpress,dc=com", "-D", "cn=admin,dc=planetexpress,dc=com", "-w", "GoodNewsEveryone","(objectClass=inetOrgPerson)" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
    restart: always
    mem_limit: 384m
    cpu_shares: 128
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    mem_limit: 64m
    cpu_shares: 128
    depends_on:
      openldap:
        condition: service_healthy

  chatbot:
    image: com.silong.llm/chatbot:1.0.0
    ports:
      - "8989:8989"
      - "27891:27891"
    volumes:
      - /opt/data/logs:/var/log/app/gc
      - ./src/main/resources/application.properties:/etc/application.properties:ro
    environment:
      SPRING.CONFIG.IMPORT: file:/etc/application.properties
    mem_limit: 512m
    cpu_shares: 128
    depends_on:
      redis:
        condition: service_healthy
    restart: always
